### ISSUE TITLE
el-bmapv-circle-layer 圆图层无法根据地图的zoom自由变大变小

### ISSUE THREAD

**Issue by RyanJeson** [yangyanggu/vue-mapvgl#1]
作者提供的示例里面，圆圈层是固定大小的。如果把地图显示全国的话 就会因为太小而看不到。 如果把size调整到全国都能看到的大小，把地图缩小范围后，原图层不会因为zoom的变化而变化，size是固定的。

我查看百度地图的原图层https://mapv.baidu.com/gl/examples/editor.html#circle.html
里面是可以根据地图缩放而放大与缩小的

**Comment by yangyanggu** [comment]
图层有个unit属性，那个属性如果设置为px就是固定大小，如果设置为m就是根据地图缩放

**Comment by RyanJeson** [comment]
是的，我刚刚自己看到了。 实在抱歉

> 图层有个unit属性，那个属性如果设置为px就是固定大小，如果设置为m就是根据地图缩放
